### ISSUE TITLE
Story: User-defined functions

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/ILE#3]
- Add pane for Function definition. Scrollable. Always editable.
- The pane has a **Submit** button - initially disabled. As soon as any  text is entered/edited . Submit is enable. At the same time, a global internal flag changes UDF code status to 'Uncompiled', and this class is added to the pane (e.g. to permit the border or background or code colour to change.
- (Contrary to original sketch - there is now no separate 'Feedback' pane). Any feedback message from the compiler will be shown in a sub-pane at the bottom of the Function Definition pane. 
- If the compile is successful, the simple, language-indepent 'Compiled OK' will be shown, the internal status will change to 'Compiled', and the **Submit** button disabled (until next edited).
- _When the status is 'Compiled'_, then if an  _expression_ is submitted from the **Expression Evaluator** pane, the function definitions will be included along with the wrapped expression and submitted to the compile/run server. This ceases as soon as the status goes back to 'Uncompiled'. In this way the user will never be seeing both (function) compile errors and expression errors at the same time. Note, however, that if the status has gone back to 'Uncompiled' and the user evaluates a previously successful expression, they will get a compiler error _for the expression_ of the form 'No such function: foo'.

**Comment by richardpawson** [comment]
Currently the UDFs are going into their own class, which means that:

- they can't be accessed from the expression evaluator without prefixing the function call with the classname
- they need to be made public (in C#), where I want to avoid the need for access modifiers

So I think we need to insert the UDF(s) into the same class as the expression evaluation.

**Comment by richardpawson** [comment]
Got this (expected) compile error:

`prog.cs(12,9): error CS1519: Unexpected symbol `3' in class, struct, or interface member declaration`

But the first bit - `prog.cs(12,9):`  is unhelpful.  Options:

- Just reduce it to: `error CS1519: Unexpected symbol `3' in class, struct, or interface member declaration`
- Be clever and adjust both the line number and character number (for indentation) based on the wrapping code template and present this in a clearer form e.g.

`Line(1, 1): error CS1519: Unexpected symbol `3' in class, struct, or interface member declaration`

- As above but highlight the appropriate line (in many cases, only line!) from the appropriate character.

**Comment by richardpawson** [comment]
Sometimes the JOBE server takes many seconds to respond. It would be helpful if as soon as a submission is made, that the mouse-pointer and/or the indicator on the tab changes to the spinning wheel.  Alternatively, display a message 'Waiting for compile server response', until a response is received.

 (this applies to Expression and Function panes - and will apply to Test later)

**Comment by richardpawson** [comment]
Further to above - I think the server was actually down. 

But in attempting to submit code _that could not possibly compile_ I was getting back a 'Compiled OK' message after several seconds.  Is it defaulting to 'Compiled OK' on a time-out?

**Comment by scascarini** [comment]
Yes I need to improve robustness when server is down, doing now.
