### ISSUE TITLE
Story: Loading a Task

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/ILE#5]
given `task=[id]` in the query string (where `Id `is a string, not a number), the client loads from a server the various elements associated with that Task. These elements should probably be defined in a `.json` file.  However, the file should be loaded _indirectly_  (e.g. via a service), as it might be that, at a later point, it will first need to check that the task has been assigned by a teacher to the student logged in. These are the elements

- The `language` this task applies to - which will force the switch when the task is loaded (same task for different language will have a different `TaskId`.
- Task `title` e.g. '_Game of Life - Part I_' - to appear in the header of the Task pane
- The 'description' as `.html` + its own `.css` (with default) to be displayed in the **Task** pane, which is scrollable, never-editable. 
- Additional `wrapping` code (to add to the default e.g. using/import, function definitions, data definitions
- Any additional (over default) `disallowed ` code patterns (as RegEx + Message rules)
- (Optional) `skeleton `code to appear in the **Function definition** pane from the start
- _If there is any skeleton code_ then a **Reset** button will appear, which will clear the **Function definition** pane and reset it to the skeleton code.
- Whether function defs are restricted to returning an `expression` (i.e. no code block) - defaults to `true`
- Whether the user may `paste` into the **Expression** and/or **Function Def** panes (defaults to `false `for both).

**Comment by richardpawson** [comment]
Renaming of headings in `rules.json`:

`FilterRules ` => `ServerResponseMessageFilters`

`ParsingRules ` => `CodeMustMatch`

`ValidationRules` => `CodeMustNotContain`

(I don't see the need to include the `Rules` suffix - but OK to keep it if you prefer.

**Comment by richardpawson** [comment]
In addition to being displayed on the screen (as now), the selected programming language should (if it isn't already) be global variable within the code, and this global variable should set a class at the top level of the application e.g.:

`<div _ngcontent-plf-c54="" class="ile python">`

This is so that any fixed or variable element (especially task-related) may show/hide (using global or local` .css`) elements according to the language.

For example, while the files for e.g. wrapping code and tests will be different for each language version of the same task, the description and hints might be a single file but with multiple snippets of explanatory code marked up with the appropriate language.

**Comment by scascarini** [comment]
There is no convention for string keys in json files but we should be consistent. I suggest PascalCase ?

**Comment by richardpawson** [comment]
Fine

**Comment by scascarini** [comment]
Should 'wrapping' code be added to expressions or functions, both or have separate entries for each ?

**Comment by scascarini** [comment]
I've currently implemented the task specific code rules such that they can pick up Messages from the original rules file. if not found they will look in the Messages in the task file.

**Comment by richardpawson** [comment]
"Should 'wrapping' code be added to expressions or functions, both or have separate entries for each ?"

I _think_ (for the moment) that wrapping code just goes into the `MainWrapper `class as additional methods.

The idea is that you can call the methods, or use the (immutable) values from within your expressions or your function code. Tests will (later) be added in the same way.

**Comment by richardpawson** [comment]
If the `task.json` file specifies a `NextTask `property (containing a link to another `.json` file) then render a **NextTask** button at the bottom of the **Task** pane, next to **Hint1**. Clicking the button takes you to the new task.

For the time being, this button can be always shown and enabled. At a future point the sequencing will be refined.
